import {existsSync, readFileSync, readdirSync, statSync} from 'node:fs';
import path from 'node:path';
import {parse} from 'yaml';

export interface Skill {
  name: string;
  description: string;
  path: string;
  group: 'vstack' | 'independent' | 'specialty';
}

const byName = (left: string, right: string): number => left < right ? -1 : left > right ? 1 : 0;

export function discover(root: string): Skill[] {
  const skills: Skill[] = [];
  const names = new Set<string>();
  const sources: [Skill['group'], string][] = [
    ['vstack', path.join(root, 'vstack/skills')],
    ['independent', path.join(root, 'skills')],
    ['specialty', path.join(root, 'specialties')],
  ];

  function visit(directory: string, group: Skill['group']): void {
    if (!existsSync(directory)) return;
    const entries = readdirSync(directory, {withFileTypes: true});
    const skillFile = path.join(directory, 'SKILL.md');
    if (entries.some(entry => entry.name === 'SKILL.md' && statSync(skillFile).isFile())) {
      const text = readFileSync(skillFile, 'utf8');
      const frontmatter = /^---\r?\n([\s\S]*?)^---[ \t]*(?:\r?\n|$)/m.exec(text);
      if (!frontmatter || frontmatter.index !== 0) {
        throw new Error(`${directory}: expected YAML frontmatter`);
      }
      let metadata: unknown;
      try {
        metadata = parse(frontmatter[1]!);
      } catch (error) {
        throw new Error(`${directory}: ${error instanceof Error ? error.message : String(error)}`);
      }
      if (!metadata || typeof metadata !== 'object' || Array.isArray(metadata)) {
        throw new Error(`${directory}: expected YAML frontmatter mapping`);
      }
      const {name, description} = metadata as Record<string, unknown>;
      if (typeof name !== 'string') throw new Error(`${directory}: missing or invalid name in SKILL.md`);
      if (name !== path.basename(directory) || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(name)) {
        throw new Error(`${directory}: name must match its kebab-case directory`);
      }
      if (names.has(name)) throw new Error(`duplicate skill name: ${name}`);
      if (typeof description !== 'string' || !description.trim()) {
        throw new Error(`${directory}: description must not be empty`);
      }
      names.add(name);
      skills.push({name, description, path: directory, group});
      return; // A skill owns its resources; nested SKILL.md files are not installable.
    }
    const children = entries.filter(entry => entry.isDirectory()
      && !entry.name.startsWith('.') && !['node_modules', '__pycache__'].includes(entry.name));
    children.sort((left, right) => byName(left.name, right.name));
    for (const child of children) visit(path.join(directory, child.name), group);
  }

  for (const [group, source] of sources) visit(source, group);
  if (!skills.length) throw new Error('no skills found');
  return skills.sort((left, right) => byName(left.name, right.name));
}

export function discoverCommands(root: string, host: 'claude' | 'codex'): string[] {
  const source = path.join(root, 'commands', host);
  const commands: string[] = [];
  function visit(directory: string): void {
    if (!existsSync(directory)) return;
    const entries = readdirSync(directory, {withFileTypes: true});
    entries.sort((left, right) => byName(left.name, right.name));
    for (const entry of entries) {
      const filename = path.join(directory, entry.name);
      if (entry.name.endsWith('.md')) {
        if (directory !== source) {
          throw new Error(`Keep commands directly in ${source}; nested command found: ${filename}`);
        }
        if (statSync(filename, {throwIfNoEntry: false})?.isFile()) commands.push(filename);
      }
      if (entry.isDirectory()) visit(filename);
    }
  }
  visit(source);
  return commands.sort(byName);
}

export function indexText(root: string, skills: Skill[]): string {
  const lines = [
    '# Specialty workflows', '',
    'Generated by `kix sync`. Read only the workflow matching the task, then its required skills.', '',
  ];
  for (const skill of skills) {
    if (skill.group === 'specialty' && skill.name.endsWith('-workflow')) {
      const relative = path.relative(path.join(root, 'specialties'), path.join(skill.path, 'SKILL.md'));
      lines.push(`- [${skill.name}](${relative.split(path.sep).join('/')}): ${skill.description.trim().replace(/\s+/g, ' ')}`);
    }
  }
  if (lines.length === 4) lines.push('No specialty workflows installed yet.');
  return `${lines.join('\n')}\n`;
}
