from dataclasses import dataclass
import json
import os
from pathlib import Path
import re


@dataclass(frozen=True)
class Skill:
    name: str
    description: str
    path: Path
    specialty: bool


def scalar(header, key):
    match = re.search(rf'^{key}:\s*(.*)$', header, re.MULTILINE)
    if not match:
        raise ValueError(f'missing {key} in SKILL.md')
    value = match.group(1).strip()
    if value in ('>', '|', '>-', '|-', '>+', '|+'):
        rest = header[match.end():].splitlines()
        lines = []
        for line in rest:
            if line and not line[0].isspace():
                break
            lines.append(line.strip())
        return ' '.join(lines).strip()
    if value.startswith('"'):
        return json.loads(value)
    if value.startswith("'") and value.endswith("'"):
        return value[1:-1].replace("''", "'")
    return value


def discover(root):
    skills = []
    names = set()
    for source in (root / 'vstack/skills', root / 'specialties'):
        for directory, children, files in os.walk(source, followlinks=False):
            children[:] = sorted(name for name in children if not name.startswith('.') and name not in ('node_modules', '__pycache__'))
            if 'SKILL.md' not in files:
                continue
            children[:] = []
            path = Path(directory)
            text = (path / 'SKILL.md').read_text()
            parts = text.split('---', 2)
            if not text.startswith('---\n') or len(parts) != 3:
                raise ValueError(f'{path}: expected YAML frontmatter')
            try:
                name = scalar(parts[1], 'name')
                description = scalar(parts[1], 'description')
            except (ValueError, TypeError) as error:
                raise ValueError(f'{path}: {error}') from error
            if name != path.name or not re.fullmatch('[a-z0-9]+(?:-[a-z0-9]+)*', name):
                raise ValueError(f'{path}: name must match its kebab-case directory')
            if name in names:
                raise ValueError(f'duplicate skill name: {name}')
            if not description:
                raise ValueError(f'{path}: description must not be empty')
            names.add(name)
            skills.append(Skill(name, description, path, source.name == 'specialties'))
    if not skills:
        raise ValueError('no skills found')
    return sorted(skills, key=lambda skill: skill.name)


def index_text(root, skills):
    lines = ['# Specialty workflows', '', 'Generated by `kix sync`. Read only the workflow matching the task, then its required skills.', '']
    for skill in skills:
        if skill.specialty and skill.name.endswith('-workflow'):
            path = (skill.path / 'SKILL.md').relative_to(root / 'specialties').as_posix()
            lines.append(f'- [{skill.name}]({path}): {" ".join(skill.description.split())}')
    if len(lines) == 4:
        lines.append('No specialty workflows installed yet.')
    return '\n'.join(lines) + '\n'
